package com.lei.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.id
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.emp_name
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.gender
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.email
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emp.d_id
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.id
     *
     * @return the value of tb_emp.id
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.id
     *
     * @param id the value for tb_emp.id
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.emp_name
     *
     * @return the value of tb_emp.emp_name
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.emp_name
     *
     * @param empName the value for tb_emp.emp_name
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.gender
     *
     * @return the value of tb_emp.gender
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.gender
     *
     * @param gender the value for tb_emp.gender
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.email
     *
     * @return the value of tb_emp.email
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.email
     *
     * @param email the value for tb_emp.email
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emp.d_id
     *
     * @return the value of tb_emp.d_id
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emp.d_id
     *
     * @param dId the value for tb_emp.d_id
     *
     * @mbg.generated Mon Dec 25 16:18:30 CST 2017
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}